#!/usr/bin/env bash
set -e


: ${num:=${1:-$(date +%-1d)}}
name=day${num}

if [ ! -e ${name}.hs ]; then
    sed < template.hs > ${name}.hs -e "s/XXX/${name}/g"
    ln -sf ${name}.hs today.hs
else
    >&2 echo "${name}.hs already exists"
fi
if false && [ ! -e ${name}.txt ]; then
    aocd $num > ${name}.txt
else
    >&2 echo "${name}.txt already exists"
fi
