#!/usr/bin/env bash
set -e

num=$(date +%-1d)
name=day${num}
if [ ! -e ${name}.hs ]; then
    sed < template.hs > ${name}.hs -e "s/XXX/${num}/g"
    ln -sf ${name}.hs today.hs
else
    >&2 echo "${name}.hs already exists"
fi
if [ ! -e ${name}.txt ]; then
    aocd $(date +%-1d) > ${name}.txt
else
    >&2 echo "${name}.txt already exists"
fi
